# Generated by Django 4.2.1 on 2023-05-24 17:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietar', models.CharField(max_length=254, verbose_name='proprietário')),
                ('orgao', models.CharField(max_length=254, verbose_name='orgão')),
                ('data_perfu', models.DateField(verbose_name='data de perfuração')),
                ('profundida', models.FloatField(verbose_name='profundidade (m)')),
                ('q_m3h', models.FloatField(verbose_name='q (m3/h)')),
                ('equipament', models.CharField(max_length=254, verbose_name='equipamento')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='geom')),
            ],
        ),
    ]
